### ISSUE TITLE
Game crashes if you click Attack after killing an NPC

### ISSUE THREAD

**Issue by aldrichdev** [OrN/rscplus#4] opened 2016-03-13 21:34 UTC
Fight any NPC. When it's almost dead, right click it. RIGHT after it dies, click Attack. The client crashes and I have to restart.

This is really annoying when there are multiple npcs on one tile and I click the wrong one in training.

**Comment by OrN** [comment] 2016-03-14 02:14
Is this present in the normal game client?

**Comment by aldrichdev** [comment] 2016-03-14 13:57
I'll check when I get home. I'd be really surprised with all the years classic was active that no one discovered or reported this bug.

**Comment by aldrichdev** [comment] 2016-03-15 00:08
Ok, it is in the normal game client. Sorry, I should have checked that first.

I have reported the bug to Jagex so hopefully it gets fixed soon.

**Comment by lmsv-mx123** [comment] 2016-06-15 16:13
I wonder if this can get fixed on the client side, what I assume that occurs is that the client intents to send an attack action on an npc that is no longer there, so it crashes. I'll see if this can be patched.

**Comment by lmsv-mx123** [comment] 2016-06-15 18:46
It could be patched but no guarantees. It is indeed caused by nullpointer client.b:3152 client.i:9017 client.I:109 client.f:5278 client.b:5977 e.run:227 java.lang.Thread.run | java.lang.NullPointerException and what Im thinking is that is when it tries to obtain the npc object for attacking but obtains null as it's no longer there and when trying to put the action to the npc it crashes.

**Comment by OrN** [comment] 2016-06-16 04:16
Yeah, we can definetly just fix it ourselves

**Comment by OrN** [comment] 2018-05-13 22:40
Fixed by https://github.com/OrN/rscplus/pull/60

**Closed by OrN** 2018-05-13 22:40 UTC
Labels: enhancement
